[project]
name = "scrapegraph-mcp"
version = "1.0.0"
description = "MCP server for ScapeGraph API integration"
license = {text = "MIT"}
readme = "README.md"
authors = [
    { name = "Marco Perini", email = "marco.perini@scrapegraphai.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.0.0",
    "httpx>=0.24.0",
    "uvicorn>=0.27.0",
    "pydantic>=2.0.0",
    "smithery>=0.4.2",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.1.0",
    "mypy>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/ScrapeGraphAI/scrapegraph-mcp"
"Bug Tracker" = "https://github.com/ScrapeGraphAI/scrapegraph-mcp/issues"

[project.scripts]
scrapegraph-mcp = "scrapegraph_mcp.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/scrapegraph_mcp"]

[tool.hatch.build]
only-packages = true

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "I", "B", "W"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.smithery]
server = "scrapegraph_mcp.server:create_server"